version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Zipping the function"
      - zip -r lambda.zip .

artifacts:
  files:
    - lambda.zip
